export { Ghosty } from './Ghosty';
export type { GhostyProps, MascotFace } from './Ghosty';
export { Ghosty2 } from './ghosty2/Ghosty2';
export type { Ghosty2Props } from './ghosty2/Ghosty2';
export { YellowMascot } from './YellowMascot';
export type { YellowMascotProps } from './YellowMascot';
export { lerpViseme, VISEMES, visemePath } from './visemes';
export type { VisemeId, VisemeShape } from './visemes';
export { getMascotPalette } from './mascotPalette';
export type { MascotColor, MascotPalette } from './mascotPalette';
